device: 'cuda:0'
epochs: 25
lr: 0.001
batch_size: 128

latent_dim: 64
enc_hidden_dims:
- 64
dec_hidden_dims:
- 64

log_dir: ${paths.logs}/runs_ae
checkpoint_dir: ${paths.checkpoints}/checkpoint_dir_ae

# modality encoders
he_encoder: uni           # uni | virchow
rna_encoder: scgpt        # scgpt | nicheformer

alignment_mode: full   # full | recon_only

loss_weight_presets:

  full:
    recon1: 0.5
    recon2: 0.5
    cross12: 0.25
    cross21: 0.25
    align: 1.0

  recon_only:
    recon1: 1.0
    recon2: 1.0
    cross12: 0.0
    cross21: 0.0
    align: 0.0

loss_weights: ${training.loss_weight_presets.${training.alignment_mode}}

